# This is demo workflow 2 for GitHub Actions.
name: demo-2
on:
  workflow_dispatch:
  #push:

jobs:
  clone-my-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -lart