# This is demo workflow 3 for GitHub Actions.
name: demo3
on: 
    workflow_dispatch:
    
    push:
        branches: [ main ]

jobs:
    check-self-hosted:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - run: ls -lart
            - run: pwd && ls -la