# This workflow clones the repository and lists its files using GitHub Actions.
name: Clone and List Files

on:
#   push:
#     branches: []
    #branches-ignore: []

  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * *'

jobs:
  cloning:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -lart