# This workflow demonstrates passing files between jobs using artifacts in GitHub Actions.
name: Pass File Between Jobs

on: workflow_dispatch

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: job-data

      - name: Read data
        run: cat number.txt