name: List Artifacts

on:
  workflow_dispatch:

jobs:
  list-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: sudo apt install gh -y

      - name: List All Artifacts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[].name'