name: List Artifacts

on:
  workflow_dispatch:

jobs:
  list-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: sudo apt install gh -y

      - name: Authenticate with GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth login --with-token <<< "$GH_TOKEN"

      - name: List Artifacts
        run: gh api repos/${{ github.repository }}/actions/artifacts --paginate --jq '.artifacts[].name'